import React from "react";
import '../styles/about.css'

const About = (props) => {

    return <div className="about-content">
        <p> FROM THE GRACEFUL CONTOURS OF WINGS IN MIDFLIGHT TO THE SPLENDID MOSAIC OF SCALED SKIN, PHOTOGRAPHER MICHAEL KERN REVEALS ELEMENTS OF ART BROUGHT TO LIFE. WHAT BEGAN AS A CHILDHOOD FASCINATION WITH REPTILES AND AMPHIBIANS HAS EVOLVED INTO A WORLDWIDE RENOWNED COLLECTION OF NATURE PHOTOGRAPHY AND A COMMITMENT TO CONSERVATION.
        </p>
        <p> ENTITLED “THE GARDENS OF EDEN,” KERN’S BODY OF WORK INCLUDES INTIMATE PORTRAITS THAT CAPTURE THE SPIRIT, DIVERSITY, AND IMMENSE BEAUTY OF NATURE. HIS SIGNATURE BLACK BACKDROP AND CREATIVE LIGHTING ILLUMINE A VIBRANT PALETTE OF FEATHERS, SCALES AND AMPHIBIOUS PATTERNS THAT ONLY NATURE COULD CREATE.
        </p>
        <p> BY DAZZLING VIEWERS WITH HIS INTIMATE PORTRAITS, KERN HOPES TO INSTILL REVERENCE FOR ALL ANIMALS AND DISPEL THE MISCONCEPTIONS THAT VILIFY SOME OF HIS FAVORITE SUBJECTS. IN THE ABSTRACT REALITY COLLECTION, FRACTURED IMAGES AND REFLECTIONS OF SCALE AND FEATHER DETAIL EVOKE WONDER, NOT FEAR.
        </p>
        <p> KERN’S VIVID IMAGES ALSO HAVE CAPTIVATED READERS OF MANY PROMINENT NATURE MAGAZINES, CALENDARS AND JOURNALS. HIS IMAGES HAVE BEEN UTILIZED AND ARE ON DISPLAY AT SEVERAL OF THE LEADING MUSEUMS AROUND THE GLOBE.
        </p>
        <p> BEYOND THE LENS, KERN SUPPORTS VARIOUS CONSERVATION EFFORTS THROUGHOUT THE BAY AREA. LEVERAGING HIS PREVIOUS EXPERIENCE AS A HIGH TECH CONSULTANT, HE HAS SERVED ON THE BOARD OF DIRECTORS OF THE SAN FRANCISCO BAY BIRD OBSERVATORY, AS CHIEF OPERATING OFFICER OF THE INTERNATIONAL REPTILE CONSERVATION FOUNDATION AND AS ADVISOR TO THE BOARD FOR PANDEMONIUM AVIARIES.
        </p>
        <p> FOR THE PAST FOUR YEARS, MICHAEL WAS THE HEAD OF PHOTOGRAPHY AND ADVANCED VISUAL TECHNOLOGIES FOR ESSEX PROPERTY TRUST IN PALO ALTO, CALIFORNIA.
        </p>

    </div>
};

export default About;